name: CS Journey Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify Markdown files
        run: |
          echo "Running markdownlint..."
          sudo apt-get update -qq
          sudo apt-get install -y markdownlint-cli || true
          markdownlint '**/*.md' || true
